// あるある6枚のイラスト：1枚目を基準（参照）にして、残り5枚を images.edit で同じ絵柄にそろえる
const fs = require("fs"), path = require("path");
const lb = "C:/Users/mgomi/dev/lovebu-manga-builder/lovebu-manga-builder";
if (!process.env.OPENAI_API_KEY) { try { require(path.join(lb,"node_modules","dotenv")).config({path:path.join(lb,".env")}); } catch(e){} }
const OpenAI = require(path.join(lb,"node_modules","openai"));
const { toFile } = OpenAI;
const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY, timeout: 600000 });
const MODEL = "gpt-image-2.5-sunburst";
const STYLE = ` Style: flat vector illustration for a Japanese corporate SaaS website. Strictly limited palette: royal blue #0B3FA8, pale blue #EEF3FC, white, mid grey #8b93a1, and ONE small coral accent #E85B52 used only on the single most important element. Plain white background with generous margins. One simple, friendly, gender-neutral office worker drawn as a minimal geometric figure (round head, no facial features except two dot eyes; short dark-blue hair; white shirt). Clean shapes, no gradients, no shadows, no outlines thicker than needed, no texture. Absolutely no text, letters, numbers, logos, or brand marks anywhere, including on screens (screens show only grey bars and dots). Landscape 3:2, the scene centered and readable at small size.`;
const SCENES = [
 ["aru1", "A sticky note is peeling off the edge of a laptop screen and drifting away into the air, dissolving into small pieces; the worker at the desk is looking the other way at another screen. A small coral clock icon on the wall. Meaning: a task left for later slips away and is forgotten."],
 ["aru2", "The worker cheerfully carries a small light box, while behind them a tall wobbly stack of much larger heavy boxes leans and grows, casting the worker's shoulders down slightly. The top heavy box is coral. Meaning: doing the light tasks first while the heavy tasks pile up."],
 ["aru3", "The worker is digging through a tall filing cabinet and a pile of old chat-window cards and folders, one hand scratching their head, with a long paper trail on the floor; a small coral hourglass beside them. Meaning: having to look up the past history and documents before being able to reply, which takes time."],
 ["aru4", "The worker leans back from a huge scroll of an extremely long document covered with dense grey text-bars that unrolls off the desk onto the floor; their two dot eyes are tired spirals; one coral highlight marks a single short line hidden in the middle. Meaning: text generated by AI is long and dense and hard to read."],
 ["aru5", "The worker walks on a treadmill-like loop between two laptops, carrying a stack of papers from the left laptop (chat window) to the right laptop (AI chat window with a sparkle icon), papers flying; a coral arrow loops between the two. Meaning: the human has become the person who copies and pastes messages into AI."],
 ["aru6", "The worker stands before a large black box with tangled blue lines coming out of it, shrugging, and tosses a paper airplane into the box without looking; a coral question mark above their head. Meaning: not understanding what the AI is saying or doing, and just sending it anyway."],
];
const outDir = path.join(__dirname, "img", "aru"); fs.mkdirSync(outDir, {recursive:true});
async function gen(spec){ const r = await client.images.generate({ model: MODEL, prompt: spec+STYLE, size: "1536x1024", quality: "high" }); return Buffer.from(r.data[0].b64_json,"base64"); }
async function edit(spec, refPath){ const img = await toFile(fs.readFileSync(refPath), "ref.png", {type:"image/png"});
  const r = await client.images.edit({ model: MODEL, image: img, prompt: "Draw a NEW scene in exactly the same illustration style, palette, line weight and the same character design as the reference image (do not copy the reference's scene; only its style and character). Scene: "+spec+STYLE, size: "1536x1024", quality: "high" }); return Buffer.from(r.data[0].b64_json,"base64"); }
(async () => {
  const ref = path.join(outDir, "aru1.png");
  if (!fs.existsSync(ref)) { fs.writeFileSync(ref, await gen(SCENES[0][1])); console.log("ok ref aru1"); } else console.log("skip aru1");
  await Promise.all(SCENES.slice(1).map(async ([name, spec]) => { const f = path.join(outDir, name+".png"); if (fs.existsSync(f)) { console.log("skip", name); return; }
    try { fs.writeFileSync(f, await edit(spec, ref)); console.log("ok", name); } catch(e){ console.error("fail", name, String(e.message).slice(0,200)); } }));
  console.log("DONE");
})();
